version: '3.4'

services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    container_name: user.api
    build:
      context: .
      dockerfile: user.api/Dockerfile

    ports:
      - 5000:5000
      - 5001:5001

  user.sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: user.sqlserver.db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd.User"
      ACCEPT_EULA: "Y"
      
    ports:
      - 5010:5010

  restaurant.api:
    image: ${DOCKER_REGISTRY-}restaurantapi
    container_name: restaurant.api
    build:
      context: .
      dockerfile: restaurant.api/Dockerfile

    ports:
        - 6000:6000
        - 6001:6001 
 
  restaurant.sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: restaurant.sqlserver.db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd.restaurant"
      ACCEPT_EULA: "Y"
      
    ports:
      - 1433:1433

